version: "3.7"

volumes:
  postgres_data: {}

services:
  postgres:
    ports:
      - 5432:5432
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=debugdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=psql01
